export const AUTH_TOKENS = {
    AUTHENTICATE_USER_USECASE: Symbol('AUTHENTICATE_USER_USECASE'),
    AUTH_USER_REPOSITORY: Symbol('AUTH_USER_REPOSITORY'),
    PASSWORD_SERVICE: Symbol('PASSWORD_SERVICE'),
    TOKEN_SERVICE: Symbol('TOKEN_SERVICE'),
};
