export const USERS_TOKENS = {
    // Contracts
    USER_REPOSITORY: Symbol('USER_REPOSITORY'),
    PASSWORD_HASHER: Symbol('PASSWORD_HASHER'),
    LOGGER: Symbol('LOGGER'),

    // Use Cases
    CREATE_USER_USECASE: Symbol('CREATE_USER_USECASE'),
    UPDATE_USER_USECASE: Symbol('UPDATE_USER_USECASE'),
    DELETE_USER_USECASE: Symbol('DELETE_USER_USECASE'),
    FIND_USER_USECASE: Symbol('FIND_USER_USECASE'),
    LIST_USERS_USECASE: Symbol('LIST_USERS_USECASE'),
};
