export const DASHBOARD_TOKENS = {
    DASHBOARD_REPOSITORY: Symbol('DASHBOARD_REPOSITORY'),
    GET_DASHBOARD_METRICS_USECASE: Symbol('GET_DASHBOARD_METRICS_USECASE'),
    GET_LAST_ADMINISTRATIVE_UPDATE_USECASE: Symbol('GET_LAST_ADMINISTRATIVE_UPDATE_USECASE'),
};
