export const COMPLAINTS_TOKENS = {
  // Contratos
  COMPLAINT_REPOSITORY: Symbol('COMPLAINT_REPOSITORY'),
  COMPLAINT_EVIDENCE_REPOSITORY: Symbol('COMPLAINT_EVIDENCE_REPOSITORY'),
  INTERNAL_COMMENT_REPOSITORY: Symbol('INTERNAL_COMMENT_REPOSITORY'),
  AUDIT_REPOSITORY: Symbol('AUDIT_REPOSITORY'),
  LOGGER: Symbol('LOGGER'),

  // Casos de uso
  CREATE_COMPLAINT_USECASE: Symbol('CREATE_COMPLAINT_USECASE'),
  LIST_COMPLAINTS_USECASE: Symbol('LIST_COMPLAINTS_USECASE'),
  UPLOAD_EVIDENCE_USECASE: Symbol('UPLOAD_EVIDENCE_USECASE'),
  UPDATE_COMPLAINT_STATUS_USECASE: Symbol('UPDATE_COMPLAINT_STATUS_USECASE'),
  ADD_INTERNAL_COMMENT_USECASE: Symbol('ADD_INTERNAL_COMMENT_USECASE'),
  LIST_INTERNAL_COMMENTS_USECASE: Symbol('LIST_INTERNAL_COMMENTS_USECASE'),
  LIST_AUDIT_LOGS_USECASE: Symbol('LIST_AUDIT_LOGS_USECASE'),
  GET_COMPLAINT_BY_ID_USECASE: Symbol('GET_COMPLAINT_BY_ID_USECASE'),
};
